resources:
  - name: spring_petclinic_ci_cd_k8s_chart_repo
    type: GitRepo
    configuration:
      gitProvider: talitzgithub
      path: talitz/spring-petclinic-ci-cd-k8s-chart
      branches:
        include: master

pipelines:
  - name: helm_chart_ci
    steps:
      - name: publish_helm_chart
        type: HelmPublish
        configuration:
          runtime:
            type: image
            image:
              custom:
                name: releases-docker.jfrog.io/jfrog/pipelines-u18node
                tag: "12.18.2"
                autoPull: true
          helmVersion: 3     
          lint: true
          inputResources:
            - name: spring_petclinic_ci_cd_k8s_chart_repo
          outputResources:
            - name: spring_helm_chart_resource
          chartPath: spring-petclinic-ci-cd-k8s-chart          
